<?php

/**
 * @file
 * The module file for binder.
 */

/**
 * Implements hook_theme().
 */
function bhge_digital_binder_theme($existing, $type, $theme, $path) {

  return [
    'article_list' => [
      'variables' => ['items' => [], 'title' => ''],
    ],
    'digital_binder_form' => [
      'variables' => ['binderForm' => []],
      'template' => 'digital_binder_form',
    ],
    'digital_binder_merged_pdf' => [
      'variables' => ['merged_pdf' => NULL],
      'template' => 'digital_binder_merged_pdf',
    ],
    'digital_binder_list' => [
      'variables' => ['search_results_list' => []],
      'template' => 'digital_binder_list',
    ],
  ];
}

/**
 * Implements hook_preprocess_page().
 */
function bhge_digital_binder_preprocess_page(&$variables) {
  if (\Drupal::service('path.current')->getPath() == "/binder-form") {
    $variables['#attached']['library'][] = 'bhge_digital_binder/bhge-digital-binder';
  }
  elseif (\Drupal::service('path.current')->getPath() == "/digital-binder-list") {
    $variables['#attached']['library'][] = 'bhge_digital_binder/bhge-digital-binder-list';
  }
}
