<?php

/**
 * @file
 * Custom gemc_c115_120_gallery module.
 */

/**
 * Implements hook_theme().
 */
function gemc_product_listing_page_theme($existing, $type, $theme, &$path) {

  $path = 'themes/custom/gemc';
  $theme = [
    'gemc_product_listing_page' => [
      'variables' => [
        'c114_dropdown' => [],
        'c115_120_gallery' => [],
        'c04_contact' => [],
      ],
      'template' => 'pages/product-listing-page',
    ],
  ];
  return $theme;
}

/**
 * Implements hook_preprocess_page().
 */
function gemc_product_listing_page_preprocess_page(&$variables) {
  if (\Drupal::routeMatch()->getRouteName() == 'gemc_product_listing_page.products') {
    $variables['hide_default_block'] = TRUE;
  }
}
