<?php

/**
 * @file
 * Custom bhge_c34_product_comparison module.
 *
 * This module has an abstraction layer that allows to reuse code for
 * GEMC site.
 * In order to customize product comparison you can create/extend your own
 * product comparison services and set them in Drupal settings like
 *   $settings['product_comparison_data_service_name'] = service.name;
 *   $settings['product_comparison_data_helpers_service_name'] = service2.name;
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Site\Settings;
use Drupal\paragraphs\Entity\Paragraph;
use Drupal\file\Entity\File;

/**
 * Implements hook_entity_extra_field_info().
 *
 * Adds new extra field that can be used to display products comparison table.
 */
function bhge_c34_product_comparison_entity_extra_field_info() {
  $extra = [];

  $extra['node']['product']['display']['bhge_product_comparison'] = [
    'label' => t('BHGE Product comparison'),
    'description' => t('Product comparison table.'),
    'weight' => 5,
    'visible' => TRUE,
  ];

  return $extra;
}

/**
 * Implements hook_theme().
 */
function bhge_c34_product_comparison_theme() {
  $theme = [
    'bhge_product_comparison' => [
      'variables' => [
        'count' => NULL,
        'download_title' => NULL,
        'download_url' => NULL,
        'product_entity' => NULL,
        'product' => NULL,
        'products' => NULL,
        'attribute_labels' => NULL,
      ],
      'template' => 'c34-product-comparison',
    ],
  ];
  return $theme;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function bhge_c34_product_comparison_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($view_mode == 'full') {
    if ($display->getComponent('bhge_product_comparison')) {
      $product_comparison_data_service_name = Settings::get('product_comparison_data_service_name', 'bhge_c34_product_comparison.comparison_data');
      $product_comparison_data_helpers_service_name = Settings::get('product_comparison_data_helpers_service_name', 'bhge_c34_product_comparison.comparison_data_helpers');

      $field_prod_section = $entity->get('field_prod_section');
      if ($field_prod_section->first()) {
        $parentSectionId = $field_prod_section->first()->getValue()['target_id'];
      }

      // Check if this product has attributes, else skip.
      $field_product_attributes = $entity->get('field_product_attributes');
      if ($field_product_attributes->first()) {
        if (!empty($parentSectionId)) {
          $data = \Drupal::service($product_comparison_data_service_name)->getRelatedProducts($parentSectionId);
          $grouped_data = \Drupal::service($product_comparison_data_helpers_service_name)->groupData($data, $entity->id());
          $products = $grouped_data['products'];
          $attribute_labels = $grouped_data['attributes'];

          // Only show if theres something to compare.
          if (count($products) > 1 && count($attribute_labels)) {
            $download_url = $download_title = '';
            // Get download field data.
            if ($entity->hasField('field_product_information')) {
              $field_product_information = $entity->get('field_product_information');
              if ($field_product_information->first()) {
                $paragraphId = $field_product_information->first()
                  ->getValue()['target_id'];
                $paragraph = Paragraph::load($paragraphId);
                $field_cta_download = $paragraph->get('field_cta_download');
                if ($field_cta_download->first()) {
                  $fileId = $field_cta_download->first()
                    ->getValue()['target_id'];
                  $file = File::load($fileId);
                  $download_url = $file->url();
                  $download_title = $entity->getTitle() . ' ' . t('Brochure');
                }
              }
            }

            $product = $products[$entity->id()];
            // Build total gallery.
            $build['bhge_product_comparison'] = [
              '#theme' => 'bhge_product_comparison',
              '#count' => count($products),
              '#download_title' => $download_title,
              '#download_url' => $download_url,
              '#product_entity' => $entity,
              '#product' => $product,
              '#products' => $products,
              '#attribute_labels' => $attribute_labels,

            ];
          }
        }
      }
    }

  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bhge_c34_product_comparison_preprocess_node(&$variables) {
  $node = $variables['node'];

  if ($variables['view_mode'] == 'full' && $node->getType() == 'product') {
    $variables['section_type'] = '';
    if (isset($variables['content']['bhge_product_comparison']['#filter_initial'])) {
      $variables['section_type'] = $variables['content']['bhge_product_comparison']['#filter_initial'];
    }
  }
}
