<?php

/**
 * @file
 * Custom bhge_c55_featured_video module.
 */

/**
 * Implements hooks_preprocess_paragraph().
 */
function bhge_c55_featured_video_preprocess_paragraph(&$variables) {
  if (!empty($variables['elements']['#paragraph'])) {

    /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
    $paragraph = $variables['elements']['#paragraph'];
    $id = $paragraph->get('type')->getValue();
    $parent = NULL;

    if ($id[0]['target_id'] == 'block_featured_video') {
      $variables['has_filters'] = 0;
      $variables['category'] = NULL;
      $variables['limit'] = 60;
      $variables['offset'] = 0;
      $variables['topics'] = NULL;
      $variables['pid'] = $paragraph->id();

      $dataHelpers = \Drupal::service('bhge_core.data_helpers');
      $c55Helpers = \Drupal::service('bhge_c55_gallery.gallery_data_helpers');
      $cards = $paragraph->field_single_card;
      foreach ($cards as $card) {
        $card = $card->entity;
        $image = $dataHelpers->getImage($card, 'field_image', 'field_dam_image', 'digital_video_image');
        $video = '';

        $description = $dataHelpers->getDescription($card);

        if (!empty($card->field_video[0])) {
          $contentType = 'video';
          $video = $card->field_video[0]->value;
          $description = $card->field_description->value;
        }
        elseif (!empty($image)) {
          $contentType = 'image';
        }
        else {
          $contentType = 'text';
        }

        $row = [
          'contentType' => $contentType,
          'image' => $image,
          'video' => $video,
          'title' => $card->field_title->value,
          'type' => $card->field_label->value,
          'gradient' => !empty($card->field_gradient_background_image->value) ? 'has-gradient' : '',
          'description' => $description,
          'buttons' => $dataHelpers->getLinks($card),
        ];
        if ($contentType == 'video') {
          $c55Helpers->processVideoUrl($row);
        }
        $variables['dataset']['results'][] = $row;
      }

      $variables['dataset']['total'] = count($cards);
    }
  }
}
