<?php

/**
 * @file
 * Custom bhge_document_center.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_paragraph().
 */
function bhge_upcoming_events_preprocess_paragraph(&$variables) {
  if (!empty($variables['elements']['#paragraph'])) {
    /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
    $paragraph = $variables['elements']['#paragraph'];
    $id = $paragraph->get('type')->getValue();
    $parent = NULL;
    if ($id[0]['target_id'] === 'block_upcoming_events') {
      // $variables['#attached']['library'][] =.
      // 'bhge_upcoming_events/bhge-views-upcoming-events';.
      $variables['#attached']['library'][] = 'bhge_upcoming_events/bhge-upcoming-events';
    }
  }
  // Defining veriables for theme path.
  $theme = \Drupal::theme()->getActiveTheme();
  $theme_path = $theme->getPath();
  $variables['#attached']['drupalSettings']['bhge_upcoming_events']['theme_path'] = $theme_path;
}

/**
 * Implements hook_preprocess_node().
 */
function bhge_upcoming_events_preprocess_node(&$variables) {
  $node = $variables['node'];
  // Check content type.
  if ($node->getType() == 'event') {
    $variables['#attached']['library'][] = 'bhge_upcoming_events/bhge-events-summary';
  }
}

/**
 * Implements hook_form_alter().
 */
function bhge_upcoming_events_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $view_names = ['events_listing'];
  $view = $form_state->getStorage('view');
  if ($form_id == 'views_exposed_form' && in_array($view['view']->id(), $view_names)) {
    $theme = \Drupal::theme()->getActiveTheme();
    $theme_path = $theme->getPath();
    $form['actions']['submit']['#type'] = 'image_button';
    $form['actions']['#weight'] = '0';
    $form['actions']['submit']['#src'] = $theme_path . '/image/case-study/search.png';
    $form['actions']['submit']['#attributes']['class'][] = 'search-button';
  }
}
