bh_settings.general_settings_form:
  route_name : bh_settings.general_settings_form
  title: General Settings
  base_route: bh_settings.general_settings_form
  weight: 10
bh_settings.external_api_settings_form:
  route_name: bh_settings.external_api_settings_form
  title: External API Settings
  base_route: bh_settings.general_settings_form
  weight: 20
