bh_settings.general_settings_form:
  path: '/admin/config/bh-general-settings'
  defaults:
    _form: '\Drupal\bh_settings\Form\BhGeneralSettingsForm'
    _title: 'BH settings'
  requirements:
    _permission: 'administer bh settings'
bh_settings.external_api_settings_form:
  path: '/admin/config/bh-external-api-settings'
  defaults:
    _form: '\Drupal\bh_settings\Form\BhExternalAPISettingsForm'
    _title: 'BH External API settings'
  requirements:
    _permission: 'administer bh settings'
