<?php

/**
 * @file
 * Implementing our hooks.
 */

/**
 * Implements hook_theme().
 */
function module_hero_theme($existing, $type, $theme, $path) {

  return [
    'hero_list' => [
      'variables' => ['items' => [], 'title' => ''],
    ]
  ];
}

/**
 * Implements hook_form_alter
 */
function module_hero_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  if ($form_id == 'node_article_form') {
    $form['field_tags']['#access'] = FALSE;
    $form['title']['widget'][0]['value']['#title'] = t('Article title');
//    kint($form); die();
    $form['#validate'][] = '_module_hero_article_validate';
  }

}
