<?php

/**
 * @file
 * Custom bhge_c55_people module.
 */

use Drupal\Component\Utility\Unicode;

/**
 * Implements hook_preprocess_paragraph().
 */
function bhge_c55_people_preprocess_paragraph(&$variables) {
  if (!empty($variables['elements']['#paragraph'])) {

    /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
    $paragraph = $variables['elements']['#paragraph'];
    $id = $paragraph->get('type')->getValue();
    $parent = NULL;

    if ($id[0]['target_id'] == 'people') {
      $variables['has_filters'] = 0;
      $variables['sort_by'] = 'created';
      $variables['category'] = NULL;
      $variables['display_mode'] = 2;
      $variables['limit'] = 60;
      $variables['offset'] = 0;
      $variables['topics'] = NULL;

      $dataHelpers = \Drupal::service('bhge_core.data_helpers');
      $people = $paragraph->field_person;
      foreach ($people as $person) {
        $person = $person->entity;
        $variables['dataset']['results'][] = [
          'contentType' => 'person',
          'image' => $dataHelpers->getImage($person),
          'title' => $person->getTitle() . ' ' . $person->field_last_name->value,
          'position' => $person->field_role->value,
          'description' => _bhge_c55_people_get_description($person->field_bio->value),
          'type' => !empty($person->field_team->entity) ? $person->field_team->entity->getName() : '',
          'links' => [['title' => t('View Bio'), 'url' => $person->toUrl()->toString()]],
        ];
      }

      $variables['dataset']['total'] = count($people);
    }
  }
}

/**
 * Get stripped tags from rich text field.
 *
 * @param string $description
 *   The description needs to be stripped.
 *
 * @return string
 *   Returns the cleaned up description.
 */
function _bhge_c55_people_get_description($description) {
  $strippedTags = str_replace("&nbsp;", "", strip_tags($description));
  return Unicode::truncate($strippedTags, 250, TRUE, TRUE);
}
