<?php

/**
 * @file
 * Custom ge_file_browser module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function ge_file_browser_form_alter(&$form, FormStateInterface &$form_state) {
  if (isset($form['#form_id'])) {
    if ($form['#form_id'] == 'entity_browser_image_browser_form' ||
       $form['#form_id'] == 'entity_browser_image_browser_modal_form') {
      file_browser_attach_file_browser_to_form($form);
    }
  }
}
